# Numpy
- create array
- maths
- operations

In [2]:
x=[[1,2,3],
   [3,2,1]]
print(x)

[[1, 2, 3], [3, 2, 1]]


without numpy doing maths(matrix maths) is vey complex in any language

In [3]:
import numpy as np


In [4]:
x = np.array([
    [1,2,3],
    [3,4,5]])
print(x)
print(type(x))
print(x.shape)

[[1 2 3]
 [3 4 5]]
<class 'numpy.ndarray'>
(2, 3)


In [5]:
print(x.sum())
print(x.sum(axis=0)) # sum of each coloumn
print(x.sum(axis=1)) # sum of each row

18
[4 6 8]
[ 6 12]


In [6]:
a = np.array([1, 2, 3]) #Simple matrix
b = np.array([[1,1],[2,2],[3,3]]) # 2d matrixs
c = np.array([[[1,1],[2,2],[3,3]]]) # 3d matrix
print(a.shape, a.ndim)
print(b.shape, b.ndim)
print(c.shape, c.ndim)

(3,) 1
(3, 2) 2
(1, 3, 2) 3


# matrix creation
- sequential
    - arange
    - linspace
- random
    - rand
    - randint
    - uniform


In [7]:
#Exclusive function
x = np.arange(1,11,0.5) # start, end, step
print(x)
# Inclusive function
y = np.linspace(0,10,6) # start, end, number of points
print(y)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]
[ 0.  2.  4.  6.  8. 10.]


In [8]:
np.arange(1,11,0.5).reshape(4,5) # reshape to 4 X 5 matrix

array([[ 1. ,  1.5,  2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5, 10. , 10.5]])

In [9]:
x1 = np.array([[1,2,3], [3,4,5]])
x2= np.array([[4,2,6], [3,8,6]])

In [10]:
print(x1)
print(x2)
print(x1+x2)
print(x1-x2)
print(x1*x2)
print(x1/x2)
print(x1//x2)
print(x1**x2)
print(x1>x2)
print(x1<x2)
print(x1>=x2)
print(x1<=x2)

[[1 2 3]
 [3 4 5]]
[[4 2 6]
 [3 8 6]]
[[ 5  4  9]
 [ 6 12 11]]
[[-3  0 -3]
 [ 0 -4 -1]]
[[ 4  4 18]
 [ 9 32 30]]
[[0.25       1.         0.5       ]
 [1.         0.5        0.83333333]]
[[0 1 0]
 [1 0 0]]
[[    1     4   729]
 [   27 65536 15625]]
[[False False False]
 [False False False]]
[[ True False  True]
 [False  True  True]]
[[False  True False]
 [ True False False]]
[[ True  True  True]
 [ True  True  True]]


In [16]:
a = np.random.rand(3,3)
a

array([[0.99, 0.64, 0.05],
       [0.85, 0.46, 0.5 ],
       [0.01, 0.79, 0.06]])

In [12]:
s = np.set_printoptions(precision=2)

In [13]:
b = np.random.randint(0,10,(3,3))
b

array([[3, 4, 5],
       [3, 4, 9],
       [8, 4, 5]])

In [14]:
c = np.random.uniform(0,10,(5,5))
c

array([[0.73, 5.32, 2.11, 0.28, 4.76],
       [7.66, 4.77, 5.55, 6.38, 9.37],
       [3.78, 1.42, 5.9 , 6.57, 8.84],
       [7.25, 9.46, 1.66, 6.37, 6.37],
       [0.04, 9.98, 6.39, 2.85, 8.25]])