In [2]:
import numpy as np

In [3]:
#1
a = np.array([[0,0],
             [0,0],
             [0,0],
             [0,0],
             [0,0]])
print(a)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [4]:
#2
a = np.array([[1,1],
             [1,1],
             [1,1],
             [1,1],
             [1,1]])
print(a)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [5]:
#3
x = np.random.randint(1,9,(3,3))
print(x)

[[2 5 8]
 [4 6 6]
 [1 2 7]]


In [6]:
#4
x = np.random.randint(1,9,(3,3))
print(x)
x = x[::-1]
print(x)

[[7 1 2]
 [4 6 2]
 [5 5 6]]
[[5 5 6]
 [4 6 2]
 [7 1 2]]


In [7]:
#5
a = np.random.randint(0,50,(5,5))
print(a)
a[a%2!=0]


[[ 6 20 12 34 18]
 [ 6 13  5 11 15]
 [ 8 49  5 20 25]
 [ 4 37 27 45 30]
 [ 7 41 42 47  0]]


array([13,  5, 11, 15, 49,  5, 25, 37, 27, 45,  7, 41, 47])

In [8]:
#6
a = np.random.randint(0,50,(5,5))
print(a)
print(a.mean())
print(a.sum())
print(a.min())
print(a.max())
print(a.std())


[[ 8 47 22 21 46]
 [34 34 30 35 40]
 [44 16 43 40 39]
 [ 7 37 47 14 10]
 [24  5  5 13 20]]
27.24
681
5
47
14.255609422259015


In [9]:
#7
a = np.random.randint(0,50,(5,5))
print(a)
print(f'Minimum Value: {a.min()}')
print(f'Maximum Value: {a.max()}')

[[27 32 10 34 45]
 [25  1 24 11 11]
 [16  8 40  4 20]
 [24 29  8 13 19]
 [28 22  8 44 38]]
Minimum Value: 1
Maximum Value: 45


In [10]:
#8
a=np.random.randint(0,20,(2,2))
a

array([[ 2, 18],
       [ 8,  5]])

In [11]:
#9
a = np.random.rand(4,4)
b = np.random.rand(4,4)
print(f'Matrix 1: \n{a}')
print(f'Matrix 2: \n{b}')
print(f'Mulitiplication of Matrix 1 and 2: \n{a*b}')

Matrix 1: 
[[0.36998469 0.5597563  0.51804799 0.44261661]
 [0.55881529 0.35992711 0.43350457 0.78632034]
 [0.7553246  0.30031644 0.40555015 0.91188938]
 [0.35290409 0.56086809 0.90016913 0.25109261]]
Matrix 2: 
[[0.18834487 0.92590236 0.83305725 0.99157926]
 [0.69758578 0.68400269 0.01660813 0.88372905]
 [0.23491082 0.78725443 0.54702465 0.73366261]
 [0.92216927 0.65458697 0.20732288 0.03582567]]
Mulitiplication of Matrix 1 and 2: 
[[0.06968472 0.51827967 0.43156363 0.43888945]
 [0.3898216  0.24619111 0.0071997  0.69489413]
 [0.17743393 0.23642545 0.22184593 0.66901915]
 [0.32543731 0.36713695 0.18662566 0.00899556]]


In [ ]:
#10

In [12]:
#11
a = np.random.randint(0,50,(2,2))
print(a)
a[a%2!=0]

[[ 4 45]
 [29  9]]


array([45, 29,  9])

In [13]:
#12
a = np.random.randint(0,50,(2,2))
print(a)
a[a%2==0]

[[10 16]
 [27 27]]


array([10, 16])

In [23]:
#13
a = np.random.randint(0,50,(6,6))
print(a)
a[:3,:5]

[[30 37 27 43 28  0]
 [42 19 36 40 33 49]
 [24 25 38 42 31 19]
 [21  3 14 47 27 15]
 [38  4 26 12 33 23]
 [ 2 23 39 11 36 31]]


array([[30, 37, 27, 43, 28],
       [42, 19, 36, 40, 33],
       [24, 25, 38, 42, 31]])

In [25]:
#14
a = np.random.randint(0,50,(6,6))
print(a)
a = a[::-1]
print(a)

[[10 12 47 14  3 27]
 [43 39 26 44 35 44]
 [24 11 11 35 16  8]
 [ 7 48 33  5 42  1]
 [29 14 29 43 44 37]
 [17 41 37 42 12 13]]
[[17 41 37 42 12 13]
 [29 14 29 43 44 37]
 [ 7 48 33  5 42  1]
 [24 11 11 35 16  8]
 [43 39 26 44 35 44]
 [10 12 47 14  3 27]]


In [ ]:
#15
