In [10]:
import numpy as np

In [12]:
#1
a = np.array([[0,0],
             [0,0],
             [0,0],
             [0,0],
             [0,0]])
print(a)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [13]:
#2
a = np.array([[1,1],
             [1,1],
             [1,1],
             [1,1],
             [1,1]])
print(a)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [14]:
#3
x = np.random.randint(1,9,(3,3))
print(x)

[[5 8 4]
 [5 5 7]
 [4 2 3]]


In [15]:
#4
x = np.random.randint(1,9,(3,3))
print(x)
x = x[::-1]
print(x)

[[3 3 5]
 [7 3 8]
 [6 4 5]]
[[6 4 5]
 [7 3 8]
 [3 3 5]]
