In [1]:
import numpy as np

In [2]:
#1
a = np.array([[0,0],
             [0,0],
             [0,0],
             [0,0],
             [0,0]])
print(a)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [3]:
#2
a = np.array([[1,1],
             [1,1],
             [1,1],
             [1,1],
             [1,1]])
print(a)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [4]:
#3
x = np.random.randint(1,9,(3,3))
print(x)

[[3 1 8]
 [8 6 3]
 [3 3 5]]


In [5]:
#4
x = np.random.randint(1,9,(3,3))
print(x)
x = x[::-1]
print(x)

[[6 3 3]
 [4 5 7]
 [2 4 5]]
[[2 4 5]
 [4 5 7]
 [6 3 3]]
